board/urls.py
from django.urls import path
from . import views

# 네임스페이스를 정의
# 네임스페이스를 사용할때는 board:question_detail 와 같이 사용
app_name = 'board'  # board 앱의 URL 네임스페이스 설정

urlpatterns = [
    path('', views.index, name='question_list'),  # board 앱의 index 뷰를 기본 URL로 설정
    path('<int:question_id>/', views.detail, name='question_detail'),  # 질문 상세 페이지 URL
    path('ask/create/<int:question_id>/',
         views.create_answer, name='create_answer'),  # 답변 생성 URL 
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include  # include 함수를 가져옵니다.
# from board import views  # board 앱의 views 모듈을 가져옵니다.

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('board/', views.index)  # views.py 파일의 index 함수를 의미
    path('board/', include('board.urls')),  # board 앱의 urls.py 파일을 포함
]

board/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    subject = models.CharField(max_length=200)  # 질문 제목
    content = models.TextField()  # 질문 내용
    created_at = models.DateTimeField(auto_now_add=True)  # 생성 시간
    updated_at = models.DateTimeField(auto_now=True)  # 수정 시간

    def __str__(self):
        return self.subject  # 객체를 문자열로 표현할 때 제목을 반환
    
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)  # 질문과의 관계 설정
    content = models.TextField()  # 답변 내용
    created_at = models.DateTimeField(auto_now_add=True)  # 생성 시간
    updated_at = models.DateTimeField(auto_now=True)  # 수정 시간

    def __str__(self):
        return f"Answer to {self.question.subject}"  # 객체를 문자열로 표현할 때 질문 제목을 포함한 답변을 반환    

board/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Question, Answer

def index(request):
    questions = Question.objects.order_by('-created_at')  # 질문을 생성시간 기준으로 내림차순
    return render(request, 'board/index.html', {'questions' : questions})



def detail(request, question_id):
    # question = Question.objects.get(id=question_id)  # 질문 객체 가져오기  
    question = get_object_or_404(Question, id=question_id)  # 질문 객체 가져오기, 없으면 404 에러 반환
    return render(request, 'board/detail.html', {'question': question})


def create_answer(request, question_id):
    question = get_object_or_404(Question, id=question_id)  # 질문 객체 가져오기
    Answer(question=question, 
           content=request.POST.get['content']).save()  # POST 요청에서 'content' 필드의 값 답변 저장
    return redirect('board:question_detail', question_id=question.id)  # 질문 상세 페이지로 리다이렉트

templates/board/detail.html
<!-- {% load static %}
<link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'style.css' %}"> -->
{% extends "base.html" %}
{% block content %}

<div class="container">
    <h1>{{ question.subject }}</h1>
    <p>{{ question.content }}</p>
    <h4>답변개수 : {{ question.answer_set.count }}</h4>
    <div>
        <ul>
            {% for answer in question.answer_set.all %}
                <li>{{ answer.content }}</li>
            {% endfor %}
        </ul>
    </div>

    <form method = 'post' action = '{% url "board:create_answer" question.id %}'>
        {% csrf_token %} 
        <textarea name="content" rows="20"></textarea>
        <p><input type="submit" value="댓글 작성"></p>    
    </form>
</div>
{%endblock %}

templates/board/index.html
{% if questions %}
    <ul>
        {% for question in questions %}
            <li>
                <!-- <a href = "/board/{{question.id}}"> -->
                <a href="{% url 'board:question_detail' question.id %}">
                    {{ question.subject }} - {{ question.created_at }}</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>질문이 없습니다.</p>
{% endif %}